# Generated by Django 3.0.3 on 2020-05-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active_Reflective', models.IntegerField()),
                ('Is_Reflective', models.BooleanField(default=False)),
                ('Is_Active', models.BooleanField(default=False)),
                ('Sensitive_Intutive', models.IntegerField()),
                ('Is_Sensitive', models.BooleanField(default=False)),
                ('Is_Intutive', models.BooleanField(default=False)),
                ('Global_Sequential', models.IntegerField()),
                ('Is_Global', models.BooleanField(default=False)),
                ('Is_Sequential', models.BooleanField(default=False)),
                ('Visual_Verbal', models.IntegerField()),
                ('Is_Visual', models.BooleanField(default=False)),
                ('Is_Verbal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=300)),
                ('LMID', models.CharField(max_length=300)),
                ('Title', models.CharField(max_length=300)),
                ('Structure', models.CharField(choices=[('Linear', 'Linear'), ('Hiearchy', 'Hiearchy'), ('Collection', 'Collection'), ('Atomic', 'Atomic'), ('Text', 'Text')], max_length=300, null=True)),
                ('LR_Type', models.CharField(max_length=50, null=True)),
                ('Intractive_Type', models.CharField(choices=[('Expositive', 'Expositive'), ('Intractive', 'Intractive'), ('Intractive', 'Intractive')], max_length=50, null=True)),
                ('Intractive_Level', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('Heigh', 'Heigh')], max_length=50, null=True)),
                ('Format', models.CharField(choices=[('text', 'html/text'), ('html/video', 'html/video'), ('html/graphics', 'html/graphics')], max_length=50, null=True)),
                ('Difficulty', models.CharField(choices=[('very easy', 'very easy'), ('easy', 'easy'), ('medium', 'medium'), ('difficulty', 'difficulty')], max_length=50, null=True)),
                ('Link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Session_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visted_Time', models.IntegerField(default=0)),
                ('Rating', models.IntegerField(default=0)),
                ('VisitedMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.LearningMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Session',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Visted_Materials', models.CharField(max_length=50, null=True)),
                ('Session_Logs', models.ManyToManyField(to='learner.Session_Logs')),
            ],
        ),
        migrations.AddField(
            model_name='learner',
            name='LS',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='learner.Learning_Style'),
        ),
        migrations.AddField(
            model_name='learner',
            name='Learning_Sessions',
            field=models.ManyToManyField(null=True, to='learner.Learning_Session'),
        ),
    ]
