# Generated by Django 3.0.3 on 2020-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20200526_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='Learning_Sessions',
            field=models.ManyToManyField(to='learner.Learning_Session'),
        ),
    ]
