# Generated by Django 3.0.3 on 2020-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0004_auto_20200530_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_style',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
