# Generated by Django 3.0.3 on 2020-06-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0005_learning_style_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_style',
            old_name='Active_Reflective',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='learning_style',
            old_name='Global_Sequential',
            new_name='Global',
        ),
        migrations.RenameField(
            model_name='learning_style',
            old_name='Sensitive_Intutive',
            new_name='Sensitive',
        ),
        migrations.RenameField(
            model_name='learning_style',
            old_name='Visual_Verbal',
            new_name='Visual',
        ),
    ]
