# Generated by Django 3.0.3 on 2020-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0007_auto_20200601_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='Password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
