# Generated by Django 3.0.3 on 2020-06-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0008_learner_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_Logs',
            new_name='Session_Log',
        ),
        migrations.RenameField(
            model_name='learning_session',
            old_name='Session_Logs',
            new_name='Learning_Session_Logs',
        ),
        migrations.AlterField(
            model_name='learning_session',
            name='Visted_Materials',
            field=models.CharField(default='', max_length=50),
        ),
    ]
