# Generated by Django 3.0.3 on 2020-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0010_auto_20200603_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='Branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MCS', 'Mathematics with Computer Science'), ('BCS', 'BTech Computer Science'), ('BIT', 'BTech Information Technology'), ('MCA', 'Master of Computer Applications'), ('MC', 'Mathematics with Computer'), ('Science', 'Science'), ('MTech Computer Science', 'MTech Computer Science'), ('BSc Computer Science', 'BSc Computer Science'), ('MSc Computer Science', 'MSc Computer Science')], max_length=50, null=True),
        ),
    ]
