# Generated by Django 3.0.3 on 2020-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0011_auto_20200606_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='Sid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
