# Generated by Django 3.0.3 on 2020-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0012_learner_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_session',
            name='Login_Time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learning_session',
            name='Logout_Time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
