# Generated by Django 3.0.3 on 2020-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0013_auto_20200608_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='LMID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
